name: test-40843

on:
  push:
    branches:
      - fix-40843
  workflow_dispatch:

permissions:
  contents: read

jobs:
  functionaltestonly:
    runs-on: ubuntu-24.04
    timeout-minutes: 20

    env:
      TEST_FILE: test/functional/ui/messages2_spec.lua
      TEST_FILTER: "showmode does not overwrite Visual word count"

    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup
        with:
          install_flags: "--test"

      - name: Build third-party deps
        run: |
          cmake -S cmake.deps --preset ci -D CMAKE_BUILD_TYPE=Debug
          cmake --build .deps

      - name: Build
        run: |
          cmake --preset ci -D CMAKE_BUILD_TYPE=Debug
          cmake --build build

      - name: Run #40843 test
        run: make functionaltest
